### ISSUE TITLE
GregTech Mithril Ore is unusable because mithril's MaterialTypes is wrong

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#12]
MaterialTypes is value in _MaterialProperties.cfg_ that [encodes via bitflags](https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/api/enums/Materials.java#L1300) which metaitems (dusts, crushed ores, toolheads, etc) GT5 will generate for the material. 

Mithril's default is 67, which is 1000011 expressed as decimal, and as you can see in the link above this will generate dusts, machine components, and tool heads.  
The correct value for mithril is 203, binary 11001011, which will generate dusts, machine components, crushed ores (making the ore usable), tool heads, and gears.

Any other generating non-default GT ore will also have to have this value of its material changed appropriately, specifically setting 4th bit, for it to work.

**Comment by lazerous42** [comment]
This will be addressed as a sub-class of the linked issue

**Comment by lazerous42** [comment]
Done deal, I changed the material property of mithril from 67 -> 203 and sure enough all of the extra processing products of mithril ore are now available, so you can use a full GT processing system to get the most out of mithril ore, granted I was a bit confused about the ore being unusable, you can smelt it in a normal furnace to get ingots, and I'm almost positive that TE pulverization works for doubling (I'm sure I've done it in my world and on camera, but I don't like saying anything for certain without retesting).  It also seem as though AOBD is smart enough to unregister it's own ore products when another mod registers them so no required changes there.  You can pull the changes from here are version 4.2.4 along with some ore berry bush tweaks and a few other niceties.  I still want to get the Thaumcraft fix in place (ore at least properly understood) before pushing out the fix pack for formal deployment.

Two other things
1) I have decided that anything done for #13 will be handled separately, as it's more of an organizational/polish type of thing where this was a specific piece of missing functionality
2) This is just a question.  Is there a way to get GT to show all the ore products in NEI.  This is not really something desirable for a production release, but it would be nice to know how to control it for development purposes.  Just curious if you know off the top of your head.

**Comment by Barhandar** [comment]
>granted I was a bit confused about the ore being unusable, you can smelt it in a normal furnace to get ingots, and I'm almost positive that TE pulverization works for doubling (I'm sure I've done it in my world and on camera, but I don't like saying anything for certain without retesting)

You couldn't do either to GregTech's Mithril as it was not registered as oreMithril in OD.
>This is just a question. 

`B:show_all_metaitems_in_creative_and_NEI=true` in GregTech.cfg, presumably.

**Comment by lazerous42** [comment]
Oh... I see.  Well, I dumbed.  I have added GT mithril to the oreMithril oredict entry using zzzCustomConfigs instead of Minetweaker.  This injects the new records during the boot process as opposed to at world load.  Now any mods with machines that can process oreMithril can process GT mithril
