### ISSUE TITLE
Disable Railcraft's Residual Heat block

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#16]
It allows one nobody-even-knows-about-it feature, tracking players with one of RC's helmets, and creates _dozens_ of bugs in its wake. Like Chromaticraft's pylons not being able to reactivate after rebuilding.

**Comment by lazerous42** [comment]
Fuck, really?  As I'm sure you've noticed, broken pylons are active in this pack.  I'll toggle this off in the RC configs.  I'm not really sure what this block does, and I've never seen anyone use it.

**Comment by lazerous42** [comment]
4.3.7 is now available with this block disabled.  There was also some JAS spawn table cleanup from a change made to switch off BoP vanilla biome overrides.  I have also started a special thanks section on the introduction page of the FTBUtils guide to mention users who were helpful in identifying and correcting issues.  You can grab it here, a final version of the current fix pack will be posted for formal deployment at the end of today
