### ISSUE TITLE
Void reed does not spawn in Swamplands due to BOP

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#18]
Void Reed (needed for Chromaticraft progression) does not spawn in BOP Swamplands due to BOP overriding vanilla swamp biomes with its own.  
Per here ( https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/955 ) there appears to be a simple fix:  

"As a solution in BoP, change to B:Swampland=false under "vanilla biomes to override" in config/biomesoplenty/biomegen.cfg (it's normally true). This instructs BoP (and therefore RTG in my pack) to use the vanilla swamp generator instead of the BoP override generator. Verified void reeds are now spawning as appropriate in the biome."

I know this ties into the Luminous Cliffs issue (and, in turn, Advanced Rocketry will remedy this to a degree) but I figure it's optimal to have the Void Reeds spawn naturally if it's possible.  I will post again if I get a chance to try the change.

**Comment by wholesalegerbils** [comment]
Can confirm that this fixes the void reed issue with no apparent ill effects to existing worlds.  You can test it by running "/redecorate <range> flowers" in a swampland biome after the change.

**Comment by lazerous42** [comment]
Weird, I have void reeds spawning in my world from the last round of unlocks.  I will have to explore the details of this a bit in light of this information.

**Comment by lazerous42** [comment]
Well, the change is harmless (I checked to see if it would disrupt the nosie map/biome spawn table for existing worlds) so I went ahead and deactivated BoP biome overrides on all vanilla biomes just to avoid any other weirdness.  I could not reproduce this though, I have void reeds in my world (the live LP world).  I cannot prove that those are not an artifact from some development related process that I performed so I will trust you judgment here.  You can pull the 4.2.3 configs from here, I also reduced taint frequency a bit (went from to low to to high to hopefully a nice middle ground now).
