### ISSUE TITLE
Baublelicious recipes not in line with progression

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#20]
All of the items it adds are probably a little out of line but an example is the "Ring of Flight" which requires a nether star and a few other easy ingredients (gold block, a few diamonds) and adds permanent creative flight.  The rest are pretty similiar to baubles added by Botania but have "casual" recipes.

**Comment by lazerous42** [comment]
Crap, I just forgot to do this.  I added this mod to allow for certain baubles to be consolidated into a single item.  The added items were intended to be disabled.  I'll remove them now

**Comment by lazerous42** [comment]
Version 4.3.8 has been posted with a script to disable these items for the time being.  I think this mod can be used to consolidate some Botania and Thaumcraft baubles, but if it can't then I will pull it out in a future release.  Creating a quick script is the fastest way to fix this right now in my workflow.
