### ISSUE TITLE
Extra Utilities Pseudo-Inversion Sigil Ritual Broken

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#21]
You cannot perform the pseudo-inversion sigil ritual due to the beacon not recognizing shift+right click as it appears to have been modified by et futurum.  This can be fixed easily by changing 

 B:"Colourful Beacon Beams"=true
to
 B:"Colourful Beacon Beams"=false

**Comment by wholesalegerbils** [comment]
in etfuturum.cfg

**Comment by lazerous42** [comment]
Good thing checked here first.  I was just about to send the deployment message to FTB for 5.0.1.  I'll stick this in and re-upload.

**Comment by lazerous42** [comment]
It's deactivated in 5.0.1 now.  You probably shouldn't try and grab any config updates from here until 5.0.1 gets posted by FTB, so just leave it fix it in your local configs (which I assume you already did), and that fix will be maintained in 5.0.1

**Comment by lazerous42** [comment]
Oh, just an FYI.  It looks like chisel can color beacons already, so the Et Futurum feature that was disabled didn't cause any loss of functionality
