### ISSUE TITLE
Cannot Construct RFdrills Earthshaking Crystal

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#24]
Issue:  You cannot create the Earthshaking Crystal (an upgrade component to the Dark Soularium Crusher) due Epic Siege Mod modifying Ghasts to "ESM_Ghast.name.  Normally, you combine a destructive crystal + a soul vial with a ghast inside of a soul binder but the soul binder, in this instance, does not recognize a soul vial with ESM-Ghast.name.  I have not found a way to spawn a "regular" ghast.

**Comment by lazerous42** [comment]
I'll give this a try and see what can be done.

**Comment by lazerous42** [comment]
Maybe I can just add a custom recipe that does use an ESM Ghast in a soul vial

**Comment by lazerous42** [comment]
Ok well, I can't add custom soul binder recipes.  There is no config for this as the large quantity of NTB data that exists on the soul vial is not exactly amicable to the XML files EIO uses for it's configuration.  So what I did was create a direct, one way conversion recipe to turn an ESM ghast vial into a vanilla ghast vial via a script change.  Just craft the vial in your inventory to get what you needed for the crystal.
