### ISSUE TITLE
[5.0.1] "shutting down internal server"

### ISSUE THREAD

**Issue by robbing88** [lazerous42/Ascension-of-the-Technomancer#28]
When I try to create a world the game tells me the above and throws me back to the main menu. no crash reports or anything since the game technically doesn't "crash". I have added Optifine D6 and Mo' Creatures and have also tried running the game without them to no avail. Any help would be appreciated.

**Comment by wholesalegerbils** [comment]
#25 same issue I had -- you've got to go to /minecraft/config/rftools/dimlets.cfg and then scroll to the bottom and delete the extra spaces after -1's (there's a few of them).  Or, you can just replace your dimlets.cfg with mine and it should be all set.  


[dimlets.cfg.zip](https://github.com/lazerous42/Ascension-of-the-Technomancer/files/1316551/dimlets.cfg.zip)

**Comment by robbing88** [comment]
When I tried that myself it didn't work, but your file totally did the trick! thanks a bunch

**Comment by lazerous42** [comment]
Well, that's icky.  I wonder why this didn't happen to me ever.  Let me check my dimlets file, as this was changed for 5.0.1 to make sure that all the newer AoA dimensions are blocked from RFTools.

**Comment by lazerous42** [comment]
Ya, very strange.  I'm guessing the trailing whitespace was immediately following the final dimletsettings record, but before the close brace like this

`...
    I:"dimlet.Biome.Twilight Swamp"=-1
    I:"dimlet.Biome.Vox Ponds"=-1
    I:dimlet.Biome.WyvernBiome=-1[here]
}`

My file has no trailing whitespace characters.  Could it possibly occur if you ever launched without Mo' Creatures post update, as the wyvern biome is the final record.  Of course that would mean that RFTools is not capable of dynamically maintaining it's config files.

This is strange, and troubling as I don't know what the scenario is that will cause damage to this file.  The master copy in my dev instance does not have any formatting problems.
