### ISSUE TITLE
Unobtainable Gallium

### ISSUE THREAD

**Issue by donoya** [lazerous42/Ascension-of-the-Technomancer#3]
I can't seem to find any ores or recipes for getting gallium, which is needed for various gregtech electronics.

**Comment by wholesalegerbils** [comment]
There's quite a few ways but they all require processing and yield either a small amount or have a small chance of yielding it.  These can all be done with LV machines (just keep in mind the thermal centrifuge takes 2 amps and is pretty power hungry):

Thermal centrifuge purified (or crushed, that's less optimal though) zinc ore and then macerate the centrifuged zinc ore or put it in the rock crusher.  This will yield 1x tiny pile of galium, and a 10% chance of a full dust from macerating the purified zinc.  

You can also macerate/rock crush centrifuged bauxite (sphalerite) for a 10% chance at full dust -- bauxite seems pretty common I think.

**Comment by donoya** [comment]
Ah. Thank you. I didn't realize the LV machines don't need gallium.

**Comment by lazerous42** [comment]
LV doesn't need gallium (fortunately).  There are quite a few elements that can only be obtained as byproducts of the main ores that spawn.  I recommend this chart, it's been quite helpful to me.  It maps out all of the elements comprising all of the ores.

http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing

There us also a way to click on a machine interface and see all of it's recipes (but I forget the key combo to get it to work).

**Comment by lazerous42** [comment]
FYI ~ Zinc, Bauxite, and Sphalerite(sp?) have gallium dust as a byproduct.
