### ISSUE TITLE
Turn Down Chromaticraft Dimension Structure Difficulty

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#31]
Doing the same thing, over and over and over, in slighty larger space/with slightly longer sequence, isn't difficult. It's _mind-numbingly tedious_.

To check yourself, go to Chroma dimension, locate the puzzles, and then try doing the waterflow and the music ones at difficulty 3. Or the switch-display one, though it involves significantly less tedium.

**Comment by lazerous42** [comment]
Ok, I'm going to just take your word for it here.  I know literally nothing of the Chroma dimension, and I don't really want it completely spoiled as it's on of the few things in 1.7.10 modded MC I have no experience with.  I'm going to knock it down to 2.  Can you give me some vague idea of what the structure difficulty setting controls without revealing too much of it to me?

**Comment by lazerous42** [comment]
As I mentioned above, I trust your opinions one design direction in most cases so I bumped structure difficulty down from 3 -> 2.  I don't want to go to the Chroma for testing unless it's absolutely necessary.  Reika intended for this to be a big surprise for people who stuck with it and worked through the content.  I will be recording when I go, so I want to get my natural initial response on camera.

This change is Version 5.1.2

**Comment by Barhandar** [comment]
>Can you give me some vague idea of what the structure difficulty setting controls without revealing too much of it to me?

In most cases, it controls the size/amount of iterations of the puzzles. In one of them, both. The things you have to _do_ generally don't change from the room to room, so you just have to do the same thing more times. Which is somewhat okay with the two puzzles that involve thinking, but for the rest, it's just repetitive, tedious grind.
