### ISSUE TITLE
Mobs spawn right next to players

### ISSUE THREAD

**Issue by Barhandar** [lazerous42/Ascension-of-the-Technomancer#35]
Sometimes even within attack range. For comparison, vanilla upholds 24-block distance from players.

**Comment by lazerous42** [comment]
What creature specifically spawned very close to you?  If its Grunts or Skollies, they just dash (teleport) at you, up to and including through walls.  Beyond that, I don't really know if it's something I have control over.  That's not a parameter configurable through Just Another Spawner (which is necessary for Mo' Creatures compatibility and is actually making things less dickish than vanilla AoA spawns).
I know that Random Things bloodmoons make things spawn in close proximity to the player, but JAS empties the vanilla spawn tables so it should not be having any sort of effect.  I don't think Epic Siege Mod can do this, and once again all "normal"  spawning is controlled by JAS so it can only control vanilla mob AI and attributes, not spawns.

**Comment by Barhandar** [comment]
Usually direwolves (I've checked and they don't have "spawn in the pack" setting in Ender Zoo's config, only whether already existing direwolves join in), occasionally cyclopi and chargers too. Lycanite's block-dependent mobs (afrits and the other fire and lava-based ones, for example) also love surprise-spawning right next, but they typically can't spawn anywhere else anyway.  
Lycanite's Desert Gorgomites were doing this so much (try to hit one, it's undamaged, teleported to the side and now there's a dozen instead of one) we've disabled them entirely on our server, along with some other UX-broken mobs like webspammer and screecher from dungeonmobs.

**Comment by lazerous42** [comment]
Well, dungeon mobs is being removed in the next release, the environmental spawns are pretty much supposed to do that, although the current configs have cut their spawn rates substantially in addition to make their "block requirements" substantially (ex: lava mobs need more lava for a valid spawn).  I can't really do anything about the generic spawns as there are no parameters to control the spawn radius from the player in JAS.

Dungeon mobs is being removed, as for whether or not anything will replace it, I cannot say as I am having severe personal issues now so enhancement updates will probably be limited unless things suddenly change for the better.
