### ISSUE TITLE
Server Crashing during startup

### ISSUE THREAD

**Issue by Symsyr** [lazerous42/Ascension-of-the-Technomancer#49]
Hello:

I am working on creating a small to medium server with this pack, since I enjoy GTNH and IE:E but whenever I run the startup script for the server, it fails.  

https://pastebin.com/R2AwuEAg

To note, this ONLY happens when trying to startup with Thermos and it only happens on this pack.  I can startup GTNH and IE:E just fine

Any help would be appreciated in getting this to startup successfully.

**Comment by Ieldra2** [comment]
"Lumien" is the author of Random Things. Try removing it and see if the problem persists. Also, this pack requires at least 6GB to run. 8 is better.

**Comment by Symsyr** [comment]
I was able to start it up just fine without Thermos.  It is only when I start it up with Thermos that the issue happens.

**Comment by Symsyr** [comment]
https://pastebin.com/SJ4RnhHG

That is an updated crash that I am getting with Thermos

Also, the allocation of RAM for this is just for testing purposes, I have 8GB allocated to the actual server that is up and running
