### ISSUE TITLE
Cannot make Circuit Assembling Machine II (HV era)

### ISSUE THREAD

**Issue by wholesalegerbils** [lazerous42/Ascension-of-the-Technomancer#5]
The recipe to make the Advanced Circuit Assembling Machine II (the HV era circuit maker) requires circuits that can only be made in an HV era circuit assembling machine.  The "Data Stick" circuit (the cheapest circuit that can be used in this recipe) requires 160 voltage which is beyond the MV voltage range of 128 EU.  It seems like every circuit recipe requires either under 32 EU, or well **over** 128 EU (140 EU or above).  

This makes it so one can get to the HV era in some regards but can't make things like the vacuum freezer (needed to progress further to make enderium and what-not).

**Comment by lazerous42** [comment]
Let's me take a look and see what's up.
Addendum: I feel like I saw Jason McRay (Infitech 2 author) explain this concept in relation to another machine.  Let me see if I can find the video and retrieve the answer from the depths of the interweb

**Comment by lazerous42** [comment]
No, my mistake, Jason's video was about using multiple energy hatches in a multi-block to get over the energy barrier for making higher tier materials in an electric blast furnace.  More research will be needed (i.e. I probably need to find out when he explains HV circuits ;-) ).

I certainly expect that this is just another Gregism and not a script/config bug.  I could be wrong, but stuff this deep in GT is pretty self contained.  I haven't touched too many GT configs and very few recipes.  Greg and Blood Asp put so much work into a carefully tuned progression, it's best to fit your pack around GT, rather than fitting GT into your pack.

**Comment by lazerous42** [comment]
Hmm.. I just checked in my world and the data stick is only 90 EU, not 160.  Are you one version 3.9.0?  I just checked Twitch and it is available for download.  I reviewed the GT 5.09.29 change log and Blood_Asp mentioned "Bugfixes and rebalancings for circuit changes." as one of the included items.  Could this be a recipe bug that was fixed?

**Comment by wholesalegerbils** [comment]
That did it, I must have done a sloppy update and not had the 3.9.0 changes go through so this must be fixed for 3.9.0 and onwards.  Thanks for the help!

**Comment by lazerous42** [comment]
But wait, there's more!  I just now realized that GT 5.29 is causing chunk generation based crashes in the nether.  I had no idea of this issue for like a month.  I need to report this to the GT forums to see what Blood_Asp has to say about it.  In the mean time I need to post a revert to 5.28 along with a recipe change for your issue (which is in the 3.10.0 configs I just posted).  The repoalcement is an IC2 Advenced circuit. 
 You can just grab the 5.28 version from here and drop it into your game:  https://mods.curse.com/mc-mods/minecraft/251053-gregtech-5-unofficial#t1:other-downloads

**Comment by lazerous42** [comment]
I have posted the version rollback to GT 5.28, along with the recipe bug fix for the original error report to FTB, the configs are available here for quick access.  I have also submitted the following issue report to the GregTech GitHub project page along with my test results for further review.

https://github.com/Blood-Asp/GT5-Unofficial/issues/1063

**Comment by lazerous42** [comment]
W00t! I just tested GT5u 5.09.30pre3 and it corrects the nether generation problem.  Since the pre-releases are being tested now, the formal release should be available in the near future.  I will deploy this updated version into the pack as soon as I can.

**Comment by lazerous42** [comment]
I've just checked the config files for 5.09.30pre3 and if you choose, it appears safe for you to drop in the new GT5 as a replacement for use until the formal release.  You can get it here.

https://onedrive.live.com/?id=478CC928A26B8E66%212067&cid=478CC928A26B8E66

I reviewed the config diffs between 5.09.28 and 5.09.30 and there were no disruptive changes that I willl need to make custom edits to handle.  You might want to save off a fresh copy of your world (as only a limited number of backups are ever kept with the Minecraft instance) just before the switch over for maximum safety.  I do have a bundle of fixes with some new mods that have not yet been sent for posting yet (v3.12.1).  Depending on how long it takes for the full release of GT to occur, I might wait on deploying 3.12.1 until after it is live.  This is just to give you all possible options on how to proceed in the interim.
