### ISSUE TITLE
How do I make rubber?

### ISSUE THREAD

**Issue by innfamy** [lazerous42/Ascension-of-the-Technomancer#51]
I've put sticky resin on the extractor, then it process into raw rubbber pulp, but I tried every way and can't turn it into normal rubber pulp

**Comment by LosGrak** [comment]
You need to combine 9 rubber dust and 1 sulfur dust in a chemical reactor. This makes enough molten rubber to make 9 ingots. Then you either pump that into a fluid solidifier with an ingot mold to make rubber ingots (or another mold type if you need a different rubber part, rings for instance), or you can pump it into an assembly machine along with wires and a chip configured to 24 to make rubber coated wires.

I prefer to solidify the rubber first, so I can make the wires as I need them (ingots into fluid extractor, then pumped into the assembly machine).

**Comment by innfamy** [comment]
So it's impossible to make rubber without a chemical reator? Because the fluid solidifier needs rubber rings, so I need atleast some rubber for start. I searched on NEI but I found none recipe to convert raw rubber pulp on actual rubber pulp

**Comment by LosGrak** [comment]
You cannot make rubber without the Chemical Reactor, but you don't need rubber to make the Fluid Solidifier. To make the pump for the solidifier, you can use paper rings.

**Comment by innfamy** [comment]
Thank you very much, you saved me sir

**Comment by LosGrak** [comment]
Great to hear. You can close this issue.
