### ISSUE TITLE
Mo Creatures hostile horses not spawning?

### ISSUE THREAD

**Issue by innfamy** [lazerous42/Ascension-of-the-Technomancer#52]
I've searched for a long time trying to find one of the variants (bat horse.zombie and skeleton) but couldn't find any of them. Are they really rare or is a mo creatures bug for using JAS?
If its a bug then a I suggest a change to the essences itens recipe, as they are used on the normal horses for making the pegasus, nightmare, unicorn, etc.

Ps: I did look on the JAS files and looked for the mobs on the specific biomes but couldn't find any of them.

**Comment by innfamy** [comment]
Nvm, i remeber that mo creatures do not come with the pack

**Comment by LosGrak** [comment]
You actually need to download Mo' Creatures separately and add it to the pack yourself. Additionally, you need to change the Mo' Creatures.save file located in the scripts folder to Mo' Creatures.zs. I recommend creating a copy of the .save file first.

**Comment by innfamy** [comment]
Yes, I did both but had to increase the horses spawn chances, since the lycanites ones seens to take all the space, I bumped it to 60 weight but still pretty scarse, atleast is doable since you actually need a lot of these mob drops to get the actual good horses on mo creatures
