### ISSUE TITLE
Some customized Thaumcraft recipes don't appear in NEI

### ISSUE THREAD

**Issue by lazerous42** [lazerous42/Ascension-of-the-Technomancer#7]
I have noticed that certain items appear to be uncraftable and block progression through the magical side of the content (ex. Witchery null catalyst).  These items do in fact have accessible customized recipes, but the Thaumcraft NEI Plugin seems to be kind of hit or miss with displaying them.  This is due to the mod trying to hide the recipes until they are "unlocked" in the Thaumonomicon (similar to ChromaticCraft recipes).  Since these are custom recpies, they never stop getting hidden from NEI.

My current recommended solution is to download and add ThaumicNEI as this mod doesn't try to hide the recipes and thus doesn't have this problem

https://minecraft.curseforge.com/projects/thaumic-nei

This mod will be added in the upcoming 4.x release, but for the time being you can add it in manually to correct the problem.  I just wanted to get the knowledge out there to help people out in the interim, until the update is ready.

**Comment by lazerous42** [comment]
With the deployment of version 4.x ThaumicNEI is now a standard component.  This issue will be closed

**Comment by Barhandar** [comment]
ThaumicNEI does try to hide the recipes, but does it in a different way (it also checks for whether the research exists and whether it's autounlocking). Also, the issue with TNEIP is with any and all Crucible recipes, even unmodified ones - they're only visible in it on checking 'U'sage of the ingredients, such as coal for Alumentum.

**Comment by lazerous42** [comment]
Interesting, well, the first thing I'm going to look into is the Thaumcraft stuff, just to try and gather some answers (like whether or not your original reported TC/NEI issue is in anyway controllable by me).  I'm putting aside the v5 update for a bit for a bug review and hopefully fixing session over the next week.  Last week I kind of had some life stuff occurring so I really didn't get much time to review bugs as I thought, but I can at least review things you have reported now.

**Comment by lazerous42** [comment]
So it's only crucible recipes.  An interesting observation.  Potentially valuable.  Thank you
